# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from walmart_content_management_python_sdk import Walmart

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        walmart = Walmart(
        
                        client_id = 'YOUR_API_KEY',
        
                        private_key = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(walmart)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
