# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from walmart_content_management_python_sdk.type.feeds_display_item_status_response_errors import FeedsDisplayItemStatusResponseErrors
from walmart_content_management_python_sdk.type.feeds_display_item_status_response_results import FeedsDisplayItemStatusResponseResults

class RequiredFeedsDisplayItemStatusResponse(TypedDict):
    pass

class OptionalFeedsDisplayItemStatusResponse(TypedDict, total=False):
    errors: FeedsDisplayItemStatusResponseErrors

    # Total number of feeds returned
    totalResults: int

    # The object response to the starting number, where 0 is the first available
    offset: int

    # The number of items to be returned
    limit: int

    results: FeedsDisplayItemStatusResponseResults

class FeedsDisplayItemStatusResponse(RequiredFeedsDisplayItemStatusResponse, OptionalFeedsDisplayItemStatusResponse):
    pass
