# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from walmart_content_management_python_sdk.type.feed_record_response_errors import FeedRecordResponseErrors
from walmart_content_management_python_sdk.type.feed_record_response_results import FeedRecordResponseResults

class RequiredFeedRecordResponse(TypedDict):
    pass

class OptionalFeedRecordResponse(TypedDict, total=False):
    errors: FeedRecordResponseErrors

    # Total number of feeds returned
    totalResults: int

    # The object response to the starting number, where 0 is the first available
    offset: int

    # The number of items to be returned
    limit: int

    results: FeedRecordResponseResults

class FeedRecordResponse(RequiredFeedRecordResponse, OptionalFeedRecordResponse):
    pass
