# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from walmart_content_management_python_sdk.type.feeds_get_feed_status_response_errors import FeedsGetFeedStatusResponseErrors
from walmart_content_management_python_sdk.type.feeds_get_feed_status_response_ingestion_errors import FeedsGetFeedStatusResponseIngestionErrors
from walmart_content_management_python_sdk.type.feeds_get_feed_status_response_item_details import FeedsGetFeedStatusResponseItemDetails

class RequiredFeedsGetFeedStatusResponse(TypedDict):
    pass

class OptionalFeedsGetFeedStatusResponse(TypedDict, total=False):
    errors: FeedsGetFeedStatusResponseErrors

    # A unique ID used for tracking the Feed File
    feedId: str

    # Can be one of the following: RECEIVED, INPROGRESS, PROCESSED, or ERROR
    feedStatus: str

    ingestionErrors: FeedsGetFeedStatusResponseIngestionErrors

    # The number of items received in the feed
    itemsReceived: int

    # The number of items in the feed that processed successfully
    itemsSucceeded: int

    # The number of items in the feed that failed due to a data or system error
    itemsFailed: int

    # The number of items in the feed that are still processing
    itemsProcessing: int

    # The object response to the starting number, where 0 is the first entity available for request
    offset: int

    # The number of items returned. Cannot be greater than 1000.
    limit: int

    itemDetails: FeedsGetFeedStatusResponseItemDetails

class FeedsGetFeedStatusResponse(RequiredFeedsGetFeedStatusResponse, OptionalFeedsGetFeedStatusResponse):
    pass
