# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from walmart_content_management_python_sdk.type.item_details_item_ingestion_status_item_ingestion_errors import ItemDetailsItemIngestionStatusItemIngestionErrors

class RequiredItemDetailsItemIngestionStatusItem(TypedDict):
    # Can be one of the following: DATA_ERROR, SYSTEM_ERROR, TIMEOUT_ERROR, or INPROGRESS
    ingestionStatus: str

class OptionalItemDetailsItemIngestionStatusItem(TypedDict, total=False):
    # Mart ID that a user or seller uses for a marketplace
    martId: int

    # An arbitrary alphanumeric unique ID, seller-specified, identifying each item.
    sku: str

    # An alphanumeric product ID, generated by Walmart
    wpid: str

    # index of items in the feed
    index: int

    ingestionErrors: ItemDetailsItemIngestionStatusItemIngestionErrors

class ItemDetailsItemIngestionStatusItem(RequiredItemDetailsItemIngestionStatusItem, OptionalItemDetailsItemIngestionStatusItem):
    pass
