# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import walmart_content_management_python_sdk
from walmart_content_management_python_sdk.paths.feeds_feed_id import get
from walmart_content_management_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestFeedsFeedId(ApiTestMixin, unittest.TestCase):
    """
    FeedsFeedId unit test stubs
        Feed item status
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
