# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import walmart_content_management_python_sdk
from walmart_content_management_python_sdk.model.gateway_error import GatewayError
from walmart_content_management_python_sdk import configuration


class TestGatewayError(unittest.TestCase):
    """GatewayError unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
