# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import walmart_content_management_python_sdk
from walmart_content_management_python_sdk.model.partner_feed_response_item_details_item_ingestion_status_item_ingestion_errors_ingestion_error_item import PartnerFeedResponseItemDetailsItemIngestionStatusItemIngestionErrorsIngestionErrorItem
from walmart_content_management_python_sdk import configuration


class TestPartnerFeedResponseItemDetailsItemIngestionStatusItemIngestionErrorsIngestionErrorItem(unittest.TestCase):
    """PartnerFeedResponseItemDetailsItemIngestionStatusItemIngestionErrorsIngestionErrorItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
