# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from walmart_content_management_python_sdk.pydantic.item_details_item_ingestion_status_item_ingestion_errors import ItemDetailsItemIngestionStatusItemIngestionErrors

class ItemDetailsItemIngestionStatusItem(BaseModel):
    # Can be one of the following: DATA_ERROR, SYSTEM_ERROR, TIMEOUT_ERROR, or INPROGRESS
    ingestion_status: Literal["INPROGRESS", "SUCCESS", "DATA_ERROR", "SYSTEM_ERROR", "TIMEOUT_ERROR"] = Field(alias='ingestionStatus')

    # Mart ID that a user or seller uses for a marketplace
    mart_id: typing.Optional[int] = Field(None, alias='martId')

    # An arbitrary alphanumeric unique ID, seller-specified, identifying each item.
    sku: typing.Optional[str] = Field(None, alias='sku')

    # An alphanumeric product ID, generated by Walmart
    wpid: typing.Optional[str] = Field(None, alias='wpid')

    # index of items in the feed
    index: typing.Optional[int] = Field(None, alias='index')

    ingestion_errors: typing.Optional[ItemDetailsItemIngestionStatusItemIngestionErrors] = Field(None, alias='ingestionErrors')
    class Config:
        arbitrary_types_allowed = True
