# coding: utf-8
"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from walmart_content_management_python_sdk.client_custom import ClientCustom
from walmart_content_management_python_sdk.configuration import Configuration
from walmart_content_management_python_sdk.api_client import ApiClient
from walmart_content_management_python_sdk.type_util import copy_signature
from walmart_content_management_python_sdk.apis.tags.feeds_api import FeedsApi



class Walmart(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.feeds: FeedsApi = FeedsApi(api_client)
