# coding: utf-8

"""
    Content Management

    The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from walmart_content_management_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from walmart_content_management_python_sdk.api_response import AsyncGeneratorResponse
from walmart_content_management_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from walmart_content_management_python_sdk import schemas  # noqa: F401

from walmart_content_management_python_sdk.model.feeds_get_feed_status_response import FeedsGetFeedStatusResponse as FeedsGetFeedStatusResponseSchema

from walmart_content_management_python_sdk.type.feeds_get_feed_status_response import FeedsGetFeedStatusResponse

from ...api_client import Dictionary
from walmart_content_management_python_sdk.pydantic.feeds_get_feed_status_response import FeedsGetFeedStatusResponse as FeedsGetFeedStatusResponsePydantic

from . import path

# Query params
IncludeDetailsSchema = schemas.StrSchema
OffsetSchema = schemas.StrSchema
LimitSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'includeDetails': typing.Union[IncludeDetailsSchema, str, ],
        'offset': typing.Union[OffsetSchema, str, ],
        'limit': typing.Union[LimitSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_include_details = api_client.QueryParameter(
    name="includeDetails",
    style=api_client.ParameterStyle.FORM,
    schema=IncludeDetailsSchema,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    explode=True,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
# Header params
WMCONSUMERCHANNELTYPESchema = schemas.StrSchema
WMQOSCORRELATIONIDSchema = schemas.StrSchema
WMSVCNAMESchema = schemas.StrSchema
WMSECTIMESTAMPSchema = schemas.StrSchema
WMSECAUTHSIGNATURESchema = schemas.StrSchema
WMCONSUMERIDSchema = schemas.StrSchema
RequestRequiredHeaderParams = typing_extensions.TypedDict(
    'RequestRequiredHeaderParams',
    {
        'WM_QOS.CORRELATION_ID': typing.Union[WMQOSCORRELATIONIDSchema, str, ],
        'WM_SVC.NAME': typing.Union[WMSVCNAMESchema, str, ],
        'WM_SEC.TIMESTAMP': typing.Union[WMSECTIMESTAMPSchema, str, ],
        'WM_SEC.AUTH_SIGNATURE': typing.Union[WMSECAUTHSIGNATURESchema, str, ],
        'WM_CONSUMER.ID': typing.Union[WMCONSUMERIDSchema, str, ],
    }
)
RequestOptionalHeaderParams = typing_extensions.TypedDict(
    'RequestOptionalHeaderParams',
    {
        'WM_CONSUMER.CHANNEL.TYPE': typing.Union[WMCONSUMERCHANNELTYPESchema, str, ],
    },
    total=False
)


class RequestHeaderParams(RequestRequiredHeaderParams, RequestOptionalHeaderParams):
    pass


request_header_wm_consumer_channel_type = api_client.HeaderParameter(
    name="WM_CONSUMER.CHANNEL.TYPE",
    style=api_client.ParameterStyle.SIMPLE,
    schema=WMCONSUMERCHANNELTYPESchema,
)
request_header_wm_qos_correlation_id = api_client.HeaderParameter(
    name="WM_QOS.CORRELATION_ID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=WMQOSCORRELATIONIDSchema,
    required=True,
)
request_header_wm_svc_name = api_client.HeaderParameter(
    name="WM_SVC.NAME",
    style=api_client.ParameterStyle.SIMPLE,
    schema=WMSVCNAMESchema,
    required=True,
)
request_header_wm_sec_timestamp = api_client.HeaderParameter(
    name="WM_SEC.TIMESTAMP",
    style=api_client.ParameterStyle.SIMPLE,
    schema=WMSECTIMESTAMPSchema,
    required=True,
)
request_header_wm_sec_auth_signature = api_client.HeaderParameter(
    name="WM_SEC.AUTH_SIGNATURE",
    style=api_client.ParameterStyle.SIMPLE,
    schema=WMSECAUTHSIGNATURESchema,
    required=True,
)
request_header_wm_consumer_id = api_client.HeaderParameter(
    name="WM_CONSUMER.ID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=WMCONSUMERIDSchema,
    required=True,
)
# Path params
FeedIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'feedId': typing.Union[FeedIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_feed_id = api_client.PathParameter(
    name="feedId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=FeedIdSchema,
    required=True,
)
_auth = [
    'clientId',
    'privateKey',
]
SchemaFor200ResponseBodyApplicationXml = FeedsGetFeedStatusResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: FeedsGetFeedStatusResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: FeedsGetFeedStatusResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/xml': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationXml),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/xml',
)


class BaseApi(api_client.Api):

    def _get_feed_status_mapped_args(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _header_params = {}
        _path_params = {}
        if include_details is not None:
            _query_params["includeDetails"] = include_details
        if offset is not None:
            _query_params["offset"] = offset
        if limit is not None:
            _query_params["limit"] = limit
        if wm_consumer_channel_type is not None:
            _header_params["WM_CONSUMER.CHANNEL.TYPE"] = wm_consumer_channel_type
        if wm_qos_correlation_id is not None:
            _header_params["WM_QOS.CORRELATION_ID"] = wm_qos_correlation_id
        if wm_svc_name is not None:
            _header_params["WM_SVC.NAME"] = wm_svc_name
        if wm_sec_timestamp is not None:
            _header_params["WM_SEC.TIMESTAMP"] = wm_sec_timestamp
        if wm_sec_auth_signature is not None:
            _header_params["WM_SEC.AUTH_SIGNATURE"] = wm_sec_auth_signature
        if wm_consumer_id is not None:
            _header_params["WM_CONSUMER.ID"] = wm_consumer_id
        if feed_id is not None:
            _path_params["feedId"] = feed_id
        args.query = _query_params
        args.header = _header_params
        args.path = _path_params
        return args

    async def _aget_feed_status_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Feed item status
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_feed_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_include_details,
            request_query_offset,
            request_query_limit,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_wm_consumer_channel_type,
            request_header_wm_qos_correlation_id,
            request_header_wm_svc_name,
            request_header_wm_sec_timestamp,
            request_header_wm_sec_auth_signature,
            request_header_wm_consumer_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/feeds/{feedId}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_feed_status_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Feed item status
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_feed_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_include_details,
            request_query_offset,
            request_query_limit,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_wm_consumer_channel_type,
            request_header_wm_qos_correlation_id,
            request_header_wm_svc_name,
            request_header_wm_sec_timestamp,
            request_header_wm_sec_auth_signature,
            request_header_wm_consumer_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/feeds/{feedId}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetFeedStatusRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_feed_status(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_feed_status_mapped_args(
            feed_id=feed_id,
            wm_qos_correlation_id=wm_qos_correlation_id,
            wm_svc_name=wm_svc_name,
            wm_sec_timestamp=wm_sec_timestamp,
            wm_sec_auth_signature=wm_sec_auth_signature,
            wm_consumer_id=wm_consumer_id,
            include_details=include_details,
            offset=offset,
            limit=limit,
            wm_consumer_channel_type=wm_consumer_channel_type,
        )
        return await self._aget_feed_status_oapg(
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
            **kwargs,
        )
    
    def get_feed_status(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_feed_status_mapped_args(
            feed_id=feed_id,
            wm_qos_correlation_id=wm_qos_correlation_id,
            wm_svc_name=wm_svc_name,
            wm_sec_timestamp=wm_sec_timestamp,
            wm_sec_auth_signature=wm_sec_auth_signature,
            wm_consumer_id=wm_consumer_id,
            include_details=include_details,
            offset=offset,
            limit=limit,
            wm_consumer_channel_type=wm_consumer_channel_type,
        )
        return self._get_feed_status_oapg(
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
        )

class GetFeedStatus(BaseApi):

    async def aget_feed_status(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> FeedsGetFeedStatusResponsePydantic:
        raw_response = await self.raw.aget_feed_status(
            feed_id=feed_id,
            wm_qos_correlation_id=wm_qos_correlation_id,
            wm_svc_name=wm_svc_name,
            wm_sec_timestamp=wm_sec_timestamp,
            wm_sec_auth_signature=wm_sec_auth_signature,
            wm_consumer_id=wm_consumer_id,
            include_details=include_details,
            offset=offset,
            limit=limit,
            wm_consumer_channel_type=wm_consumer_channel_type,
            **kwargs,
        )
        if validate:
            return FeedsGetFeedStatusResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(FeedsGetFeedStatusResponsePydantic, raw_response.body)
    
    
    def get_feed_status(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
        validate: bool = False,
    ) -> FeedsGetFeedStatusResponsePydantic:
        raw_response = self.raw.get_feed_status(
            feed_id=feed_id,
            wm_qos_correlation_id=wm_qos_correlation_id,
            wm_svc_name=wm_svc_name,
            wm_sec_timestamp=wm_sec_timestamp,
            wm_sec_auth_signature=wm_sec_auth_signature,
            wm_consumer_id=wm_consumer_id,
            include_details=include_details,
            offset=offset,
            limit=limit,
            wm_consumer_channel_type=wm_consumer_channel_type,
        )
        if validate:
            return FeedsGetFeedStatusResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(FeedsGetFeedStatusResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_feed_status_mapped_args(
            feed_id=feed_id,
            wm_qos_correlation_id=wm_qos_correlation_id,
            wm_svc_name=wm_svc_name,
            wm_sec_timestamp=wm_sec_timestamp,
            wm_sec_auth_signature=wm_sec_auth_signature,
            wm_consumer_id=wm_consumer_id,
            include_details=include_details,
            offset=offset,
            limit=limit,
            wm_consumer_channel_type=wm_consumer_channel_type,
        )
        return await self._aget_feed_status_oapg(
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        feed_id: str,
        wm_qos_correlation_id: str,
        wm_svc_name: str,
        wm_sec_timestamp: str,
        wm_sec_auth_signature: str,
        wm_consumer_id: str,
        include_details: typing.Optional[str] = None,
        offset: typing.Optional[str] = None,
        limit: typing.Optional[str] = None,
        wm_consumer_channel_type: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_feed_status_mapped_args(
            feed_id=feed_id,
            wm_qos_correlation_id=wm_qos_correlation_id,
            wm_svc_name=wm_svc_name,
            wm_sec_timestamp=wm_sec_timestamp,
            wm_sec_auth_signature=wm_sec_auth_signature,
            wm_consumer_id=wm_consumer_id,
            include_details=include_details,
            offset=offset,
            limit=limit,
            wm_consumer_channel_type=wm_consumer_channel_type,
        )
        return self._get_feed_status_oapg(
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
        )

